# 04 Trasforma e combina

## Setup

In [4]:
import numpy as np
import pandas as pd

In [52]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [74]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,sibilings_spouses,parents_children,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,low,low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,high,high
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,low,low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,high,high
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,low,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,medium,medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,medium,medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,medium,medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,medium,medium
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,low,low

## Creare colonne separate

In [ ]:
titanic["family_size"] = (titanic["SibSp"]) + (titanic["Parch"]) + 1 # Questa è la più semplice, non necessita di metodi come map/replace, np.where o apply

In [25]:
titanic["is_alone"] = titanic["family_size"] == 1 # Ho usato np.where perchè la consegna richiede l'uso di un metodo condizionale, e qui ci sono 2 condizioni. Se fossero state più condizioni avrei utilizzato .apply

In [13]:
titanic["embarked_full"] = titanic["Embarked"].map({"S": "Southampton", "C": "Cherbourg", "Q": "Queenstown"}) # Qui andava bene sia map che replace visto che in ogni caso il valore mancante rimane NaN. Per sicurezza ho usato map

In [62]:
def fare_calc(fare):
    if fare < 10:
        return "low"
    elif fare <= 50:
        return "medium"
    else:
        return "high"

titanic["fare_level"] = titanic["Fare"].apply(fare_calc)

# Essendoci 3 condizioni ho utilizzato .apply(), creando una funzione apposita per la condizionale

In [36]:
titanic["family_size"].value_counts()

family_size
1     537
2     161
3     102
4      29
6      22
5      15
7      12
11      7
8       6
Name: count, dtype: int64

In [37]:
titanic["is_alone"].value_counts()

is_alone
True     537
False    354
Name: count, dtype: int64

In [38]:
titanic["embarked_full"].value_counts()

embarked_full
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [39]:
titanic["fare_level"].value_counts()

fare_level
medium    395
low       336
high      160
Name: count, dtype: int64

## Trasformare valori esistenti

In [ ]:
titanic = titanic.rename(columns={"SibSp": "siblings_spouses", "Parch": "parents_children"})

In [86]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,siblings_spouses,parents_children,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,low,low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,high,high
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,low,low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,high,high
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,low,low

In [87]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'siblings_spouses', 'parents_children', 'Ticket', 'Fare', 'Cabin',
       'Embarked', 'fare_level', 'fare_level_v2'],
      dtype='str')

In [56]:
titanic["Pclass"] = titanic["Pclass"].astype("category")

In [57]:
titanic["Pclass"].dtype

CategoricalDtype(categories=[1, 2, 3], ordered=False, categories_dtype=int64)

In [65]:
titanic["fare_level_v2"] = pd.cut(
    titanic["Fare"],
    bins=[-0.01, 10, 50, float("inf")],
    labels=["low", "medium", "high"]
)

In [68]:
titanic["fare_level_v2"].value_counts()

fare_level_v2
medium    395
low       336
high      160
Name: count, dtype: int64

## Combinare DataFrame

## Riepilogo